### ISSUE TITLE
about parameter “mt_size ” meaning

### ISSUE THREAD

**Issue by sunweice** [Good9T/MD_MTA#1]
hi ! I read the article you sent and reviewed the source code. I would like to ask about the parameter 'mt_size' in **MDVRP__Train.py** — what does it mean?
in "MDVRP__Train.py"
env_params = {
    'customer_size': 100,
    'mt_size': 102,
    'depot_size': 3,
    'capacity': 50,
    'demand_min': 1,
    'demand_max': 10,
}

**Comment by wang811** [comment]
Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice

**Comment by sunweice** [comment]
> Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice

Yeah, It means ‘multi trajectory’.

**Comment by wang811** [comment]
> > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> 
> Yeah, It means ‘multi trajectory’.

Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!

**Comment by sunweice** [comment]
> > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > 
> > 
> > Yeah, It means ‘multi trajectory’.
> 
> Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!

Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.

**Comment by wang811** [comment]
> > > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > > 
> > > 
> > > Yeah, It means ‘multi trajectory’.
> > 
> > 
> > Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!
> 
> Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.

Thank you very much for your quick reply, yes, I have been studying this code recently, but it is more difficult for me, because my code base and theoretical foundation are relatively poor, and there are more code files. Good luck with your paper!

**Comment by wang811** [comment]
> > > > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > > > 
> > > > 
> > > > Yeah, It means ‘multi trajectory’.
> > > 
> > > 
> > > Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!
> > 
> > 
> > Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.
> 
> Thank you very much for your quick reply, yes, I have been studying this code recently, but it is more difficult for me, because my code base and theoretical foundation are relatively poor, and there are more code files. Good luck with your paper!

By the way, what do I need to learn if I want to fully understand the source code?

**Comment by wang811** [comment]
> > > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > > 
> > > 
> > > Yeah, It means ‘multi trajectory’.
> > 
> > 
> > Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!
> 
> Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.

By the way, what do I need to learn if I want to fully understand the source code?

**Comment by sunweice** [comment]
> > > > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > > > 
> > > > 
> > > > Yeah, It means ‘multi trajectory’.
> > > 
> > > 
> > > Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!
> > 
> > 
> > Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.
> 
> By the way, what do I need to learn if I want to fully understand the source code?

Thank you! Don't worry too much, I recommend ‘https://www.bilibili.com/video/BV1sd4y167NS/?spm_id_from=333.337.search-card.all.click&vd_source=ea7069456fca06b0 theory part 9f5132614aa968e8’, you'd better read his book. As for programming, you need more hands-on experience.

**Comment by wang811** [comment]
> > > > > > Hello, I also have the same doubt, have you found the answer? Thanks for your answer!@sunweice
> > > > > 
> > > > > 
> > > > > Yeah, It means ‘multi trajectory’.
> > > > 
> > > > 
> > > > Thank you very much for your answer. I wonder if my understanding is correct. Is each mt an independent path? If mt_size = 102, does it mean that 102 tracks are generated independently at a time? And why is mt_size=customer_size+depot_size-1? Does that have any special meaning? Thank you very much for your reply!
> > > 
> > > 
> > > Your understanding is correct, the code sets the first action to depot, so mt starts from the second action, it can only choose from the remaining customer and depot, so it needs to subtract 1. My understanding is that this approach increases agent exploration because it forces the agent to start from each node. This source code is very worthy of in-depth study, I rely on it to complete a paper, but it has a mistake in the code, that is, the author's original experimental part is a certain problem, but the general direction is reliable.
> > 
> > 
> > By the way, what do I need to learn if I want to fully understand the source code?
> 
> Thank you! Don't worry too much, I recommend ‘https://www.bilibili.com/video/BV1sd4y167NS/?spm_id_from=333.337.search-card.all.click&vd_source=ea7069456fca06b0 theory part 9f5132614aa968e8’, you'd better read his book. As for programming, you need more hands-on experience.

Brother, thank you so much. A kind-hearted person lives a long life.
